name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  dart_code_metrics: ^4.19.0
  surf_lint_rules: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - res/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/font/Roboto-Black.ttf
        - asset: res/font/Roboto-BlackItalic.ttf
        - asset: res/font/Roboto-Bold.ttf
        - asset: res/font/Roboto-BoldItalic.ttf
        - asset: res/font/Roboto-Italic.ttf
        - asset: res/font/Roboto-Light.ttf
        - asset: res/font/Roboto-LightItalic.ttf
        - asset: res/font/Roboto-Medium.ttf
        - asset: res/font/Roboto-MediumItalic.ttf
        - asset: res/font/Roboto-Regular.ttf
        - asset: res/font/Roboto-Thin.ttf
        - asset: res/font/Roboto-ThinItalic.ttf


